cargo-features = ["edition2024"]

[package]
name = "cmd"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
clap_complete = "4.5.38"
derive = "1.0.0"
dirs-next = "2.0.0"
git2 = "0.19.0"
lazy_static = "1.5.0"
rusqlite = "0.32.1"
